#!/bin/bash

# Get Names of users
cat /etc/passwd | grep '/home/' | grep -v 'cups\|syslog\|mysql\|mongodb' |
    cut -d':' -f1 >/tmp/homes.list

runByUsers() {
    # $1 is default folder of user
    # $2 is name of user
    cd $1
    ORIG="/tmp/lubuntu-win-theme-apply"
    runuser -l $2 -c "cp -rf $ORIG/.config/ $1"
    runuser -l $2 -c "cp -rf $ORIG/.gtkrc-2.0 $1"
}

#CUSER="$(w -h| grep ':0' | cut -d' ' -f1)"
#CUSERID="$(runuser -l $CUSER -c 'id -u')"


while read USUARIO; do
    if [ -d /home/$USUARIO ]; then
        runByUsers "/home/$USUARIO" "$USUARIO"
        runuser -l $USUARIO -c "rm -rf /home/$USUARIO/.cache/"
        #if [ -f /usr/bin/lxqt-panel ]; then
        #	if [ "$CURRENTUSER" == "$USUARIO" ]; then
        #		runuser -l $USUARIO -c "killall lxqt-panel"
        #		runuser -l $USUARIO -c "lxqt-panel &"
        #	fi
        #fi
    fi
done </tmp/homes.list
runByUsers "/etc/skel" "root"

cd /usr/share/lubuntu/wallpapers
if [ -f 2004-lubuntu-wire-humming.png ]; then
    mv 2004-lubuntu-wire-humming.png lubuntu-original-wallpaper.png
    mv wx_wallpaper.png 2004-lubuntu-wire-humming.png
    rm -rf /home/*/.cache
fi

if [ -f /usr/share/sddm/themes/win10/theme.conf ]; then
    cat <<EOF >/usr/share/sddm/themes/win10/theme.conf
[General]
background=/usr/share/lubuntu/wallpapers/wx_login.png

EOF
fi
