#!/bin/bash

rm -rf /etc/skel/.config/gtk-3.0/settings.ini

rm -rf /etc/skel/.config/lxqt/lxqt.conf
rm -rf /etc/skel/.config/lxqt/lxqt-config-appearance.conf
rm -rf /etc/skel/.config/lxqt/lxqt-powermanagement.conf
rm -rf /etc/skel/.config/lxqt/panel.conf
rm -rf /etc/skel/.config/lxqt/session.conf

rm -rf /etc/skel/.config/openbox/lxqt-rc.xml

rm -rf /etc/skel/.config/pcmanfm-qt/lxqt/settings.conf

rm -rf /etc/skel/.config/qterminal.org/qterminal.ini

rm -rf /etc/skel/.gtkrc-2.0

cd /usr/share/lubuntu/wallpapers/
if [ -f 2004-lubuntu-wire-humming.png ] && [ -f lubuntu-original-wallpaper.png ]; then
	mv lubuntu-original-wallpaper.png 2004-lubuntu-wire-humming.png
	rm -rf /home/*/.cache
fi

if [ -f /usr/share/sddm/themes/win10/theme.conf ]; then
	cat <<EOF >/usr/share/sddm/themes/win10/theme.conf
[General]
background=/usr/share/lubuntu/wallpapers/win10_login.png

EOF
fi
